//
//  PullListWorker.swift
//  RepositoryManager
//
//  Created by Henrique Pereira de Lima on 23/11/19.
//  Copyright (c) 2019 Henrique Pereira de Lima. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FetchPulls {
    func fetchPulls<T:Decodable>(request: PullListModels.Request, complete:@escaping ((ConnectorResult<T>) -> Void))
}

class PullListWorker: FetchPulls, FetchPhoto {
    
    func fetchPulls<T:Decodable>(request: PullListModels.Request, complete:@escaping ((ConnectorResult<T>) -> Void)) {
        let endPoint = "repos/\(request.username)/\(request.reponame)/pulls?state=\(request.state)"
        Connector.fetch(endPoint: endPoint, complete: complete)
    }
    
    func fetchPhoto(path: String, complete: @escaping (ConnectorResult<Data>) -> Void) {
        Connector.fetchData(path: path, complete: complete)
    }
    
}
